# What's the name of the church?
title: Pueblo Baptist Church
# Give a brief description of the church
description: > # this means to ignore newlines until "baseurl:"
    Pueblo Baptist Church is an independent Baptist church located in West Pueblo, Colorado.
# Leave this alone
baseurl: "" # the subpath of your site, e.g. /blog
# Change this to the domain when you are finished and ready to publish.

url: "http://pueblobaptist.org/" # the base hostname & protocol for your site | Switch to http://cranesvillebiblechurch.com/" Before running Glynn.  Afterwards change it back to http://localhost:4000/



# Airtable API Stuff
airtable:
  apikey: "keyRTLlrVS02vC3Vx"
  newhebron: "app0XIQY9VtU5jdv9"
  

# LEAVE EVERYTHING ELSE ALONE!!

# Build settings
markdown: kramdown
 
# Exclude
exclude:
  - package.json
  - node_modules
  - gulpfile.js 
  - bower_components
keep_files:
  - css
  - assets/css
  - assets/js 

page_gen:
  - data: 'featuredEvents'
    template: 'event'
    name: 'Name'
    dir: 'events'



ftp_host: 'biblebaptistmattoon.org'
ftp_dir: 'pueblobaptist.org/'
ftp_passive: false
ftp_username: 'ryahay11'
ftp_password: '@88Volvocj'